---
- name: Bootstrap Servers
  hosts: all
  remote_user: colutti
  gather_facts: false

  tasks:

  # - name: Creates the mediafolder
  #   become: true
  #   ansible.builtin.file:
  #     path: /home/colutti/media
  #     state: directory
  #     owner: colutti
  #     group: colutti
  #     mode: 0777
  #     recurse: true


  - name: Mount network share
    become: true
    ansible.builtin.mount:
      src: 192.168.1.5:/media
      path: /home/colutti/media
      fstype: nfs
      state: mounted
      opts: defaults
      dump: '0'
      passno: '0'
