---
- name: Install all services on PI2
  hosts: 192.168.1.5
  remote_user: colutti
  gather_facts: false

  tasks:

    - name: Creating a file with content
      become: false
      ansible.builtin.copy:
        dest: /home/colutti/Projects/htpc-download-box/automations/.env
        content: |
            PUID=1000
            PGID=1000
            TZ=Europe/Madrid
            ROOT=/home/colutti/media
        owner: colutti
        group: colutti
        mode: 0775

    - name: Deploy Docker Compose stack
      become: false
      community.docker.docker_compose:
        project_src: /home/colutti/Projects/htpc-download-box/automations/
        files:
          - docker-compose.yml
