---
- name: Install all services on PI2
  hosts: 192.168.1.50
  remote_user: colutti
  gather_facts: false

  tasks:

    - name: Update the download-box github repository
      become: false
      ansible.builtin.git:
        repo: https://github.com/colutti/htpc-download-box.git
        dest: /home/colutti/Projects/htpc-download-box/
        clone: false
        update: true
        force: false
        version: master

    - name: Creating a file with content
      become: false
      ansible.builtin.copy:
        dest: /home/colutti/Projects/htpc-download-box/services/.env
        content: |
            PUID=1000
            PGID=1000
            TZ=Europe/Madrid
            ROOT=/home/colutti/media
        owner: colutti
        group: colutti
        mode: 0775

    - name: Deploy Docker Compose stack
      become: false
      community.docker.docker_compose:
        project_src: /home/colutti/Projects/htpc-download-box/services/
        files:
          - docker-compose.yml
