- Media:
    - Sonarr:
        icon: sonarr.png
        href: http://localhost:8989/
        description: Series management

    - Radarr:
        icon: radarr.png
        href: http://localhost:7878
        description: Movie management

    - Portainer:
        icon: portainer.png
        href: http://192.168.1.50:9000
        description: Container management