- Media:
    - Sonarr:
        icon: sonarr.png
        href: http://192.168.1.2:8989/
        description: Series management

    - Radarr:
        icon: radarr.png
        href: http://192.168.1.2:7878
        description: Movie management

    - Deluge:
        icon: deluge.png
        href: http://192.168.1.2:8112
        description: Torrent management

    - Jackett:
        icon: jackett.png
        href: http://192.168.1.2:9117
        description: Torrent Indexer

    - Plex:
        icon: plex.png
        href: http://192.168.1.2:32400
        description: Media Server

- Docker:
    - Portainer:
        icon: pihole.png
        href: http://192.168.1.50:9000
        description: Container management

- DNS:
    - Portainer:
        icon: portainer.png
        href: http://192.168.1.50:888/admin/
        description: DNS Ad blocker
